
title = "Smartories "

[author]
name = "Sivaprakash Rajaram"
email = "svprakash1310@gmail.com"

[Machine]
site_id = "S1002"
machine_id = "1"

[Mqtt]
host = "quantanics.in"
port = 1883
username = "quantanics"
password = "quantanics123"
qos = 2
config_update_topic = "update_configs"
events_topic = "/chennai/S1002/1"
button_inputs_topic = "/chennai/S1002/button_inputs"
exceptions_topic = "firmware_exceptions"

[Modbus]
baudrate = 19200
bytesize = 8
debug = false
fncode_read = 4
fncode_write = 5
port = "COM4"
parity = "N"
signed = true
slave = 2
stopbits = 1
timeout = 1

[Current]
baudrate = 19200
bytesize = 8
debug = false
fncode_read = 4
fncode_write = 5
port = "COM4"
parity = "N"
signed = true
slave = 1
stopbits = 1
timeout = 1

[Voltage]
baudrate = 19200
bytesize = 8
debug = false
fncode_read = 4
fncode_write = 5
port = "COM4"
parity = "N"
signed = true
slave = 2
stopbits = 1
timeout = 1

[Relay]
baudrate = 9600
bytesize = 8
debug = false
fncode_read = 4
fncode_write = 5
port = "COM4"
parity = "N"
signed = true
slave = 3
stopbits = 1
timeout = 1

[fourRelay]
baudrate = 9600
bytesize = 8
debug = false
fncode_read = 4
fncode_write = 5
port = "COM4"
parity = "N"
signed = true
slave = 255
stopbits = 1
timeout = 1

[LED_Modbus]
led1 = 4
led2 = 64
led3 = 1
led4 = 2
